.\" (C) Copyright 2016 Jan Luca Naumann <j.naumann@fu-berlin.de>,
.TH NITROKEY\-APP 1 "4 October 2016" "" "nitrokey-app man page"
.SH NAME
nitrokey-app \- Application to manage the Nitrokey

.SH SYNOPSIS
.B nitrokey-app
.RI [ options ]

.SH DESCRIPTION
.B nitrokey-app
is the official application to manage the features of the Nitrokey.
Nitrokey is an open source/open hardware USB key supporting secure encryption
and signing.

.SH OPTIONS
.TP
.B \-h, \-\-help
Display the help and exit.
.TP
.B \-a, \-\-admin
Enable extra administrative functions
.TP
.B \-d, \-\-debug
Enable debug options
.TP
.B \-\-debugAll
Enable extensive debug options
.TP
.B \-\-lock\-hardware
Enable hardware lock option
.TP
.B \-\-cmd <...>
Start a command line session

.SH AUTHOR
This man page was written by Jan Luca Naumann <j.naumann@fu-berlin.de>.
